# personnaliser le site à votre marque en remplaçant
# nom_intuition par le nom de votre intuition
# mon_equipe par le nom de votre équipe
# 
intuition: Créer un nouvel Agenda pour les insaïens
nom_equipe: agenda_insa
code_equipe: 2T

theme: jekyll-theme-dinky
